# Generated by Django 5.1.3 on 2025-02-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
